import assert from 'node:assert/strict';
import { readFile, readdir } from 'node:fs/promises';
import path from 'node:path';
import test from 'node:test';
import { iconStyles } from '@mingcute/core';
const packageRoot = path.resolve(import.meta.dirname, '..');
test('adapter uses stable core contract without policy duplication', async () => { const source = await readFile(path.join(packageRoot, 'src/tooling/adapter.ts'), 'utf8'); assert.match(source, /FrameworkAdapter/); assert.doesNotMatch(source, /FrameworkAdapterV0|export const iconStyles\s*=/); assert.doesNotMatch(source, /license(?:Key|State)|registryToken|\.npmrc/); });
test('root is utility-only and icons are independent modules', async () => { const root = await readFile(path.join(packageRoot, 'dist/index.js'), 'utf8'); assert.doesNotMatch(root, /styles\/|Regular|Filled/); const files = (await readdir(path.join(packageRoot, 'dist/styles/core-regular'))).filter((file) => file.endsWith('.js')); assert.equal(files.length, 1663); const home = await readFile(path.join(packageRoot, 'dist/styles/core-regular/home-1.js'), 'utf8'); assert.doesNotMatch(home, /User1Regular|regular\.js/); });
test('package has only the shared icon dependency and public subpaths resolve', async () => { const manifest = JSON.parse(await readFile(path.join(packageRoot, 'package.json'), 'utf8')); assert.deepEqual(manifest.dependencies, { '@mingcute/icons': 'workspace:*' }); assert.equal(manifest.peerDependencies, undefined); assert.equal(manifest.exports['./*'], undefined); assert.deepEqual(Object.keys(manifest.exports), expectedFrameworkExportKeys()); const root = await import('@mingcute/web-components'); const style = await import('@mingcute/web-components/core-regular'); const direct = await import('@mingcute/web-components/core-regular/home-1'); assert.deepEqual(Object.keys(root), ['MingcuteIconElement','defineIconElement']); assert.equal(Object.keys(style).length, 3326); assert.equal(typeof direct.Home1Regular, 'function'); });
function expectedFrameworkExportKeys() { return ['.', ...iconStyles.flatMap((style) => [`./${style}`, `./${style}/*`])]; }
