import assert from 'node:assert/strict';
import { build } from 'esbuild';
import path from 'node:path';
import test from 'node:test';
const packageRoot = path.resolve(import.meta.dirname, '..');
test('one named class excludes unrelated icons and style indexes', async () => { const result = await bundle("import { Home1Regular } from '@mingcute/web-components/core-regular'; export { Home1Regular };"); const inputs = Object.keys(result.metafile.inputs); const icons = Object.entries(result.metafile.outputs['out.js'].inputs).filter(([input, details]) => details.bytesInOutput > 0 && normalized(input).includes('dist/styles/core-regular/')).map(([input]) => path.basename(input)); assert.deepEqual(icons, ['home-1.js', 'home-1.js']); for (const style of ['core-filled','core-duotone','core-light','sharp-light','core-twotone','cute-regular','cute-filled','cute-duotone','cute-light','sharp-regular','sharp-filled']) assert.ok(!inputs.some((input) => normalized(input).endsWith(`dist/styles/${style}.js`))); assert.doesNotMatch(result.code, /User1Regular|Home1Filled/); });
test('direct icon import bypasses style barrel', async () => { const result = await bundle("import { defineHome1Regular } from '@mingcute/web-components/core-regular/home-1'; export { defineHome1Regular };"); const inputs = Object.keys(result.metafile.inputs); assert.ok(inputs.some((input) => normalized(input).endsWith('dist/styles/core-regular/home-1.js'))); assert.ok(!inputs.some((input) => normalized(input).endsWith('dist/styles/core-regular.js'))); });
async function bundle(contents) { const result = await build({ stdin: { contents, resolveDir: packageRoot, sourcefile: 'entry.js' }, bundle: true, format: 'esm', platform: 'browser', treeShaking: true, metafile: true, write: false, outfile: 'out.js', logLevel: 'silent' }); return { code: result.outputFiles[0].text, metafile: result.metafile }; }
function normalized(value) { return value.replaceAll('\\','/'); }
